# Generated by Django 4.1.7 on 2024-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_discount_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='course_thumbnails/'),
        ),
    ]
