# Generated by Django 4.1.7 on 2024-12-26 12:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail'),
        ),
    ]
